### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [1]:
# Loading Tensorflow version 2.0

%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf

In [4]:
# Checking if the Tensorflow version has been updatd or not.

tf.__version__

'2.1.0'

#### Collect Fashion mnist data from tf.keras.datasets 

In [0]:
# Loading the MNIST dataset and plitting into train and test.

Mnist = tf.keras.datasets.fashion_mnist 

In [7]:
(x_train, y_train),(x_test, y_test) = Mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [8]:
# Finding out the dimensions of training and testing.

print("The shape of x_train is : ", x_train.shape)

The shape of x_train is :  (60000, 28, 28)


In [9]:
print("The shape of x_test is : ", x_test.shape)

The shape of x_test is :  (10000, 28, 28)


In [10]:
print("The shape of y_train : ", y_train.shape)

The shape of y_train :  (60000,)


In [11]:
print("The shape of y_test : ", y_test.shape)

The shape of y_test :  (10000,)


In [0]:
import numpy as np

In [14]:
# Checking the unique numerical values of the first image.

np.unique(x_train[0])

array([  0,   1,   2,   3,   4,   6,   7,  10,  12,  13,  15,  18,  23,
        29,  35,  36,  40,  41,  44,  48,  52,  54,  55,  56,  57,  58,
        61,  62,  64,  65,  66,  67,  69,  72,  73,  74,  75,  77,  80,
        82,  88,  92,  98,  99, 102, 106, 107, 109, 115, 117, 119, 121,
       122, 123, 127, 130, 134, 136, 141, 144, 145, 146, 150, 154, 155,
       156, 159, 161, 163, 164, 166, 167, 168, 169, 170, 171, 172, 173,
       175, 176, 177, 178, 179, 180, 181, 182, 183, 185, 186, 187, 188,
       189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 202,
       203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
       243, 244, 245, 246, 248, 249, 250, 255], dtype=uint8)

In [15]:
# Checking all numerical values of the first image.

x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [18]:
# Understanding how all values will look after reducing the variance.

x_c = x_train[0]/255
print(x_c)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.00392157 0.    

#### Change train and test labels into one-hot vectors

In [19]:
# Checking the unique values in y_train.

tf.unique(y_train)

Unique(y=<tf.Tensor: shape=(10,), dtype=uint8, numpy=array([9, 0, 3, 2, 7, 5, 1, 6, 4, 8], dtype=uint8)>, idx=<tf.Tensor: shape=(60000,), dtype=int32, numpy=array([0, 1, 1, ..., 2, 1, 5], dtype=int32)>)

In [0]:
# Encoding y_train and y_test.

y_train_encode = tf.keras.utils.to_categorical(y_train, num_classes=10)

In [0]:
y_test_encode = tf.keras.utils.to_categorical(y_test, num_classes=10)

#### Build the Graph

#### Initialize model, reshape & normalize data

In [22]:
x_train.shape

(60000, 28, 28)

In [0]:
from tensorflow.keras import models  

In [0]:
from tensorflow.keras import layers

In [0]:
# Normalizing the data.

x_train_normalize = tf.keras.utils.normalize(x_train)

In [0]:
x_test_normalize = tf.keras.utils.normalize(x_test)

In [0]:
# Reshaping and initilizing the model .

model= models.Sequential([layers.Flatten(input_shape=(28,28))])

In [28]:
# Checking if the values have been normalized or not.

np.unique(x_train_normalize)

array([0.00000000e+00, 7.96855248e-04, 7.97239063e-04, ...,
       9.99989382e-01, 9.99989855e-01, 1.00000000e+00])

In [29]:
np.unique(x_test_normalize)

array([0.00000000e+00, 8.20436479e-04, 8.29325397e-04, ...,
       9.99980949e-01, 9.99988218e-01, 1.00000000e+00])

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [0]:
# Adding a dropout layer and two fully connected layers with 200 and 100 neurons respectively .

model.add(layers.Dropout(0.25))
model.add(layers.Dense(200, activation= 'relu', input_shape=(28,28)))
model.add(layers.Dense(100, activation= 'relu'))


### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [0]:
# Adding the final output layer.

model.add(layers.Dense(10, activation= 'softmax'))

In [0]:
# Compiling the model. 

model.compile(optimizer= 'adam', loss= 'categorical_crossentropy', metrics=['accuracy'])

In [33]:
# Fitting the model to check how the model is performing. 

model.fit(x_train_normalize, y_train_encode, epochs=50, validation_data=(x_test_normalize, y_test_encode), batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 8s 125us/sample - loss: 0.5111 - accuracy: 0.8118 - val_loss: 0.4260 - val_accuracy: 0.8411
Epoch 2/50
60000/60000 [==============================] - 6s 92us/sample - loss: 0.3950 - accuracy: 0.8517 - val_loss: 0.3744 - val_accuracy: 0.8602
Epoch 3/50
60000/60000 [==============================] - 5s 91us/sample - loss: 0.3623 - accuracy: 0.8646 - val_loss: 0.3611 - val_accuracy: 0.8657
Epoch 4/50
60000/60000 [==============================] - 5s 91us/sample - loss: 0.3455 - accuracy: 0.8699 - val_loss: 0.3474 - val_accuracy: 0.8726
Epoch 5/50
60000/60000 [==============================] - 5s 89us/sample - loss: 0.3312 - accuracy: 0.8746 - val_loss: 0.3367 - val_accuracy: 0.8754
Epoch 6/50
60000/60000 [==============================] - 5s 90us/sample - loss: 0.3188 - accuracy: 0.8796 - val_loss: 0.3494 - val_accuracy: 0.8706
Epoch 7/50
60000/60000 [==============================]

In [34]:
# Evaluation on training set. 

evaluate = model.evaluate(x_train_normalize, y_train_encode)
print('The training loss is {}% and The training accuracy is {}%'.format(evaluate[0]*100, evaluate[1]*100))

60000/60000 [==============================] - 4s 64us/sample - loss: 0.1467 - accuracy: 0.9455
The training loss is 14.673697718828915% and The training accuracy is 94.54500079154968%


In [35]:
# Evaluation on the test set.

evaluate1= model.evaluate(x_test_normalize, y_test_encode)
print('The test loss is {}% and The test accuracy is {}%'.format(evaluate1[0]*100, evaluate[1]*100) )

10000/10000 [==============================] - 1s 71us/sample - loss: 0.3115 - accuracy: 0.8923
The test loss is 31.153352382183076% and The test accuracy is 94.54500079154968%
